DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS ACTS;


CREATE TABLE CATEGORIES(
	CATEGORY_NAME CHAR(50) PRIMARY KEY NOT NULL,
	NUM_OF_ACTS INT NOT NULL
	
);

CREATE TABLE ACTS(
	ACT_ID INT PRIMARY KEY NOT NULL,
	TIME_STAMP CHAR(20) NOT NULL,
	CAPTION CHAR(100),
	UPVOTES INT,
	IMGB64 TEXT NOT NULL DEFAULT '',
	username CHAR(50),
	category CHAR(50),
	FOREIGN KEY (category) REFERENCES CATEGORIES(CATEGORY_NAME) ON DELETE CASCADE
);
